# Generated by Django 2.0.2 on 2018-03-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20180306_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='perfis.Perfil'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to='perfis.Perfil'),
        ),
    ]
